### ISSUE TITLE
Unrecognized assembly language code

### ISSUE THREAD

**Issue by baldachin** [AnonymerNiklasistanonym/Md2Anki#22]
My code block contains assembly code and the following warning appears during conversion:
`WARNING md2anki.preprocessor: Default to text lexer (language='assembly', err=ClassNotFound("no lexer for alias ' assembly' found"))`
![image](https://github.com/AnonymerNiklasistanonym/Md2Anki/assets/1262195/4f546aa5-c1ac-4812-b5fd-0aa54f6d7db2)

**Comment by AnonymerNiklasistanonym** [comment]
I'm not sure if you already tried it but maybe the short name `asm` instead of assembly works for your code.
But maybe I'm missing something so if you have an example snippet or a more detailed description it would help.

**Comment by AnonymerNiklasistanonym** [comment]
Even if this solves the problem I should probably add that link/information to the error message in case this problem occurs again (I remember having a similar problem with another language/id).

**Comment by baldachin** [comment]
Thanks, I've currently moved the work to mdankideck to complete it as I'm having more problems with it, should continue to try if I can get a solution to a couple of the other issues.

**Comment by baldachin** [comment]
Thanks, I've found that the correct language identifier is `nasm` and the modification has solved the problem.
