### ISSUE TITLE
The `<` symbol raises an exception

### ISSUE THREAD

**Issue by baldachin** [AnonymerNiklasistanonym/Md2Anki#24]
Exception during document conversion
User warning: 
`Field contains the following invalid HTML tags. If your field data has not been HTML encoded, make sure you call html.escape(): <t<1s\)when< p=""> </t<1s\)when<>
  warnings.warn("Field contained the following invalid HTML tags. Make sure you call html.escape() if"`
It should be `<` in the content that throws the exception.

![image](https://github.com/AnonymerNiklasistanonym/Md2Anki/assets/1262195/f6bcf53f-558d-4886-a0e6-25d6fafd77b5)

**Comment by AnonymerNiklasistanonym** [comment]
Can you maybe provide the input text (or a simple example) that threw the error?
I just tried it with the latest `wip` version in a normal text and it looks like the problem was maybe fixed but just never pushed.

https://github.com/AnonymerNiklasistanonym/Md2Anki/blob/1e3510580e61cea7a85d83efc957ff1f759c970d/examples/math_formulas_example.md?plain=1#L27-L30

![image](https://github.com/AnonymerNiklasistanonym/Md2Anki/assets/22764031/cb76f677-cd4f-4152-a7f5-7e7d69a71bcb)

**Comment by baldachin** [comment]
Sorry I didn't find the original documentation on this issue and wasn't able to reproduce it. However, during testing another problem occurred described below:

An error is returned after executing the command:

`RuntimeError: Not all code sections were inserted back! (code_sections={2: '<div class="highlight highlight_inline" style=""><pre style="line-height: 125%;"><span></span>JMP FAR PTR OPR </pre></div>', 3: '<div class="highlight highlight_inline" style=""><pre style="line-height: 125%;"><span></span>JMP DWORD PTR[4000H] </pre></div>'})`

Cue unusual title content:

```
## 03-17）如果条件跳转指令的跳转目标范围超出 -128~127 的范围，该如何处埋？举例说明。

-----

段内相对短转移和条件转移的转移范围限制在 -128~127字节，超出该范围就可以改为其他转移方式。

- 段内相对近转移
  `JMP NEAR PTR OPR ; OPR 是段内某个标号` 

- 段内间接转移
  `JMP WORD PRT OPR ; 例如 JMP WORD PTR[SI]` 

- 段间转移

    - 段间直接转移，例如 `JMP FAR PTR OPR` 

    - 段间间接转移，例如 `JMP DWORD PTR[4000H]`  
```

**Comment by baldachin** [comment]
I found the file with the anomaly.
[04730_example_01.md](https://github.com/AnonymerNiklasistanonym/Md2Anki/files/12864506/04730_example_01.md)

**Comment by AnonymerNiklasistanonym** [comment]
> I found the file with the anomaly. [04730_example_01.md](https://github.com/AnonymerNiklasistanonym/Md2Anki/files/12864506/04730_example_01.md)

Hmm I kinda got no error at all running that file with the wip version of the program when I just added it as a `custom_example.md` file into the examples directory and ran all examples.

**Comment by AnonymerNiklasistanonym** [comment]
> Sorry I didn't find the original documentation on this issue and wasn't able to reproduce it. However, during testing another problem occurred described below:
> 
> An error is returned after executing the command:
> 
> `RuntimeError: Not all code sections were inserted back! (code_sections={2: '<div class="highlight highlight_inline" style=""><pre style="line-height: 125%;"><span></span>JMP FAR PTR OPR \</pre\></div>', 3: '<div class="highlight highlight_inline" style=""><pre style="line-height: 125%;"><span></span>JMP DWORD PTR[4000H] \</pre\></div>'})`
> 
> Cue unusual title content:
> 
> ```
> ## 03-17）如果条件跳转指令的跳转目标范围超出 -128~127 的范围，该如何处埋？举例说明。
> 
> -----
> 
> 段内相对短转移和条件转移的转移范围限制在 -128~127字节，超出该范围就可以改为其他转移方式。
> 
> - 段内相对近转移
>   `JMP NEAR PTR OPR ; OPR 是段内某个标号` 
> 
> - 段内间接转移
>   `JMP WORD PRT OPR ; 例如 JMP WORD PTR[SI]` 
> 
> - 段间转移
> 
>     - 段间直接转移，例如 `JMP FAR PTR OPR` 
> 
>     - 段间间接转移，例如 `JMP DWORD PTR[4000H]`  
> ```

I'm gonna check this later, getting the same error but not sure why

**Comment by baldachin** [comment]
> > I found the file with the anomaly. [04730_example_01.md](https://github.com/AnonymerNiklasistanonym/Md2Anki/files/12864506/04730_example_01.md)
> 
> Hmm I kinda got no error at all running that file with the wip version of the program when I just added it as a `custom_example.md` file into the examples directory and ran all examples.

What is 'wip version'? How can I try this version?

**Comment by AnonymerNiklasistanonym** [comment]
All my heavily untested changes between major releases can be found in this repository on the [`wip`](https://github.com/AnonymerNiklasistanonym/Md2Anki/tree/wip) git branch.

With the following commands you should be able to test/use it:

```sh
git switch wip

# Linux
python -m venv venv_build
source venv_build/bin/activate
# Windows
python -m venv venv_build
./venv_build/Scripts/Activate.ps1

python -m pip install --upgrade build
python -m build

# Uninstall old version
python -m pip uninstall md2anki
# Install local version
python -m pip install dist/md2anki-$INSERT_CURRENT_VERSION-py3-none-any.whl
```

**Comment by AnonymerNiklasistanonym** [comment]
I found the error which was that somehow the markdown to html conversion provided by the `Markdown` python package converted parts of the placeholders begin/end (`<div>...`/`...</div>`) thing to something else (`&lt;...`).
It looks like I can just remove that from the placeholder being/end part though so maybe that just fixes it but I need to run some more tests to see if I suddenly broke anything I'm currently not aware of.

**Comment by AnonymerNiklasistanonym** [comment]
I just pushed the changes to main for a new pypi release in case you want to check if this fixes your problems.

**Comment by baldachin** [comment]
I have installed version 3.0.14b0 as per the above guidelines and am testing the question bank files at hand one by one. There is another exception in one of the files:

`UserWarning: Field contained the following invalid HTML tags. Make sure you are calling html.escape() if your field data isn't already HTML-encoded: <t<1s\) p="" 时<=""> </t<1s\)> warnings.warn("Field contained the following invalid HTML tags. Make sure you are calling html.escape() if"`

which is placed in the attachment.
[04730_example_01.md](https://github.com/AnonymerNiklasistanonym/Md2Anki/files/12876798/04730_example_01.md)

**Comment by AnonymerNiklasistanonym** [comment]
It looks like the math section content is not html escaped so the solution would be to just `import html`, `html.escape(math_content)`.
I'm gonna check with some of my old notes if this results in any obvious errors otherwise I can push it.
If you wanna try it out check out the git branch `wip-escape-tags`: https://github.com/AnonymerNiklasistanonym/Md2Anki/tree/wip-escape-tags

**Comment by AnonymerNiklasistanonym** [comment]
Everything looks good on first sight but I found another bug so the release of the bugfix will be delayed until I fix that one too.

**Comment by AnonymerNiklasistanonym** [comment]
With the new version release on pypi this problem should be fixed now.

**Comment by baldachin** [comment]
The file I have on hand has been tested without an anomaly.
