### ISSUE TITLE
File contents corrupted due to processing exception

### ISSUE THREAD

**Issue by baldachin** [AnonymerNiklasistanonym/Md2Anki#25]
When I get a specific exception during an attempted conversion it appears that the original md file contents are corrupted, with only about 100 bytes of the beginning of the file remaining and the rest of the contents lost.

The question that just came up is:

`IndexError: list index out of range`

I don't know the cause of this problem yet.

**Comment by AnonymerNiklasistanonym** [comment]
If you could provide an example document I could try to debug what the source of the raised exception is.

**Comment by baldachin** [comment]
This file triggers the problem mentioned above.
[04732_knowlege_point.md](https://github.com/AnonymerNiklasistanonym/Md2Anki/files/12876886/04732_knowlege_point.md)

**Comment by AnonymerNiklasistanonym** [comment]
In case you only want to have the double colon visually I have a quick solution to the problem on the `wip-corruption` giot branch (just used for testing, will delete later): https://github.com/AnonymerNiklasistanonym/Md2Anki/tree/wip-corruption

Essentially I just insert a unicode Zero Width Space symbol inbetween the colons (https://symbl.cc/en/200B/).

https://github.com/AnonymerNiklasistanonym/Md2Anki/blob/53cfaae99a3559852689b5743a69902352348351/src/md2anki/md_parser.py#L102-L110

**Comment by AnonymerNiklasistanonym** [comment]
I understand.
I will make an issue about it but at the moment it would mean a lot of rewrites to get it to work while on the other hand I have the subdeck thing more or less working without problems.
Thank you for the detailed information.

**Comment by AnonymerNiklasistanonym** [comment]
With the new version release on pypi this problem should be fixed now meaning that no file corruption should happen while visually preserving the double colon.
I decided to do this to for example support c++ syntax in titles without accidentally converting `std::iostream` into 2 separate decks.
If you really need this though please just create a new issue with that exact problem (e.g. *allow subdeck indicator in (sub)deck heading*) and I will think about a rewrite.

I played with the idea before but there are multiple problems connected with it like the problem of storing more than one ID at the end of the name to update the right things:

```md
# deck (deck_ID)

---

# deck::subdeck (deck_ID::subdeckID)
```

But it should be possible, it just generally requires a big rewrite of the already super messy spaghetti code that is currently *working*.

**Comment by baldachin** [comment]
For me personally, the subdeck is an icing on the cake, and not having it shouldn't affect normal use. The main reason why this bug was raised is still more concerned about the protection of the original file, perhaps there will be other exceptions triggered by the inability to complete the processing of the file exceptions and destroy the file content, for the user if there is no timely backup could be disastrous, so the core concern may be the processing of the file backup or to avoid destroying the contents of the file.

**Comment by baldachin** [comment]
Found the problem, another place where double colons are used is in fill-in-the-blank questions. I hadn't noticed before that there seems to be no current support for fill-in-the-blank questions. anki's default format for fill-in-the-blank questions is `{{c1::something}}`. There is also a portion of the test file that is fill-in-the-blank, which is currently tested with an exception but not converted.

**Comment by AnonymerNiklasistanonym** [comment]
I'm not familiar with fill in the blank?
Is that a native desktop feature or a custom plugin?

**Comment by baldachin** [comment]
This is a native feature of anki. Select 'Cloze' in the 'note type' to see the cloze control in the edit field, and add it to the body as '{{c1::text}} ' format.

Sent from my iPhone

On Oct 13, 2023, at 17:57, Niklas ***@***.***> wrote:

﻿

I'm not familiar with fill in the blank?
Is that a native desktop feature or a custom plugin?

**Comment by AnonymerNiklasistanonym** [comment]
As far as I understand you want an additional export note type that supports the cloze syntax?

I'm not familiar with that syntax but I guess it shouldn't be hard to implement.

**Comment by baldachin** [comment]
I didn't realize this feature wasn't there before, but it should be a basic feature in terms of anki format support.
If you want to implement this feature you need to note that it uses a different "note type", in other similar tools need a separate command line parameter like "-cloze" to apply different templates.

Sent from my iPhone

On Oct 14, 2023, at 14:05, Niklas ***@***.***> wrote:


As far as I understand you want an additional export note type that supports the cloze syntax?

I'm not familiar with that syntax but I guess it shouldn't be hard to implement.

**Comment by AnonymerNiklasistanonym** [comment]
I'm having kinda trouble with the implementation so it's not gonna be added soon.
Is this example what you are thinking of?

```md
# Example 'Fill in the Blank' (3083273130)

## Fill in the blank text 1 (5afd1da8-f5af-4abd-8809-6e3e47d164eb)

This text is {{boring}} {{c1::boring}} {{c1::boring::like myself}}

## Fill in the blank text 2 (f55d2943-62c6-4bf8-88aa-ba4ac0b71078)

{{c1::1st deletion}} {{c2::2nd deletion}} {{c3::3rd deletion}}

## Fill in the blank text 3 (7e0c3a24-a542-4b53-84c2-0481caa86ab4)

{{c2::Mitochondria}} are the {{c3::powerhouses}} of the cell
```

Where the values after `c#::` are uncovered every click?

Storing source code documentation for later about this topic: https://github.com/kerrickstaley/genanki/pull/37/files

**Comment by baldachin** [comment]
> I'm having kinda trouble with the implementation so it's not gonna be added soon. Is this example what you are thinking of?
> 
> ```
> # Example 'Fill in the Blank' (3083273130)
> 
> ## Fill in the blank text 1 (5afd1da8-f5af-4abd-8809-6e3e47d164eb)
> 
> This text is {{boring}} {{c1::boring}} {{c1::boring::like myself}}
> 
> ## Fill in the blank text 2 (f55d2943-62c6-4bf8-88aa-ba4ac0b71078)
> 
> {{c1::1st deletion}} {{c2::2nd deletion}} {{c3::3rd deletion}}
> 
> ## Fill in the blank text 3 (7e0c3a24-a542-4b53-84c2-0481caa86ab4)
> 
> {{c2::Mitochondria}} are the {{c3::powerhouses}} of the cell
> ```
> 
> Where the values after `c#::` are uncovered every click?
> 
> Storing source code documentation for later about this topic: https://github.com/kerrickstaley/genanki/pull/37/files

The mode of 'blank text 1' is wrong, 'blank text 3' is incorrectly labeled and cannot be determined to work properly, The 'blank text 2' pattern is closer to normal use. My own understanding of how anki fill-in-the-blanks are used is something like this: usually a single blank is edited using {{c1::text}}, which appears as [...] when viewed. [...] will be switched to 'text' content when you click to view it; there are two ways to use multiple blanks:

One is to use 'c1' to mark them all (Most of the time I'll do it this way):

```markdown
Fill in the blank text 2
{{c1::1st text}} {{c1::2nd text}} {{c1::3rd text}}
```

Displayed when studying cards:

```markdown
Fill in the blank text 2
[...] [...] [...]
```

Displayed when viewed:

```markdown
Fill in the blank text 2
1st text 2nd text 3rd text
```

The second is the use of different marks:

```markdown
Fill in the blank text 2
{{c1::1st text}} {{c2::2nd text}} {{c3::3rd text}}
```

Three different cards will be generated for the three fill-in-the-blanks at study time:

Card 1

```markdown
Fill in the blank text 2
[...] 2nd text 3rd text
```

Card 2

```markdown
Fill in the blank text 2
1st text [...] 3rd text
```

Card 3

```markdown
Fill in the blank text 2
1st text 2nd text [...]
```

That's about it for all I know.

The official description is here: [Adding/Editing - Anki Manual](https://docs.ankiweb.net/editing.html?highlight=cloze#cloze-deletion)

**Comment by AnonymerNiklasistanonym** [comment]
With what kind of software do you use the cloze card decks?

I just tried it using the example from `genanki` and then retried it by switching to the default cloze node type and they both could handle only `{{c1::text}}` (but it can appear multiple times on a card).
As soon as there was a `{{c2::text}}`/`{{c3::text}}` it was just ignored and just showed the text but no animation.

(Tested on Anki desktop Version ⁨2.1.66 (70506aeb), AnkiDroid v2.16.5)

**Comment by AnonymerNiklasistanonym** [comment]
There is now a working? implementation of some sorts for the most basic functionality.
I have not tested it in combination with like source code (C++) or LaTeX math etc. since I'm not sure the basics are working right now.

I pushed the changes on the git branch `wip-cloze` if you want to test it out with your code:

https://github.com/AnonymerNiklasistanonym/Md2Anki/commit/6524136640c7af34c716f96b10c00eaa074a080d

(don't forget to use `-anki-model md2anki_type_cloze`)

**Comment by AnonymerNiklasistanonym** [comment]
Wait a second, does cloze create multiple cards where like one card is:

```text
[...] are the powerhouses of the cell -> Mitochondria are the powerhouses of the cell
```

and then another one that is:

```text
Mitochondria are the [...] of the cell -> Mitochondria are the powerhouses of the cell
```

They aren't displayed in order on my anki client but randomly mixed with other cards.

**Comment by baldachin** [comment]
Yeah, I think that's the right result. I'll send you a fill-in-the-blanks file later.

Sent from my iPhone

On Oct 15, 2023, at 06:09, Niklas ***@***.***> wrote:

﻿

Wait a second, does cloze create multiple cards where like one card is:

[...] are the powerhouses of the cell -> Mitochondria are the powerhouses of the cell


and then another one that is:

Mitochondria are the [...] of the cell -> Mitochondria are the powerhouses of the cell


They aren't displayed in order on my anki client but randomly mixed with other cards.

**Comment by baldachin** [comment]
Here are the two fill-in-the-blank files I'm currently using, the deconstructed format may not quite match up needing some tweaking.

[04732_exam_blank.md](https://github.com/AnonymerNiklasistanonym/Md2Anki/files/12908167/04732_exam_blank.md)

[04730_exam_blank.md](https://github.com/AnonymerNiklasistanonym/Md2Anki/files/12908166/04730_exam_blank.md)

**Comment by AnonymerNiklasistanonym** [comment]
I think then it works already?

Thank you for the example files, they seem to run without problems and look good at a quick glance.

I'm gonna add it to the next realease.

**Comment by AnonymerNiklasistanonym** [comment]
It's out now on pypi if you want to try it out.

**Comment by AnonymerNiklasistanonym** [comment]
I just realized that having the cloze syntax in the heading could lead to problems with the parser replacing `::` with `: EMPTY SPACE :`...
guess this needs more time

**Comment by baldachin** [comment]
I'm trying the new version, but I haven't found a way to generate the fill-in-the-blanks questions yet, and I'm still getting errors when processing the fill-in-the-blanks file.



BraveYun

From Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by AnonymerNiklasistanonym** [comment]
That was my bad, I forgot to update the package to include the newly added file.
Before I update the package so that you can run the following command without errors:

```sh
md2anki -v
# md2anki 3.0.17b
md2anki -anki-model md2anki_type_cloze 04730_exam_blank.md -o-anki=test.apkg
```

I have one more question regarding your test document (`04730_exam_blank.md`).
Do you expect the normally answer content part to only show up as extra text after clicking the card?

**Comment by baldachin** [comment]
Okay, I'll test the fill-in-the-blank questions later.
I currently add a lot of parsing content outside of the original answer part of the question, which is placed in the 'answer' template in the currently used 'mdankideck'.

![image](https://github.com/AnonymerNiklasistanonym/Md2Anki/assets/1262195/fd2995ed-82f2-4ce6-85c6-bcc98be89bb2)

![image](https://github.com/AnonymerNiklasistanonym/Md2Anki/assets/1262195/b0323ddb-f83c-4bd1-a259-0c948b11a886)

**Comment by baldachin** [comment]
I tried the fill-in-the-blanks feature and both files on hand converted and formatted correctly. One thing that is different from my previous usage pattern is that the current one seems to display the parsing information I wrote directly on the front of the card instead of displaying it when viewing the answer as I have used it in the past, so that the answer parsing is no longer helping to understand the answer, but rather becomes a hint to the answer in the question, which may not quite fit into common usage scenarios.

**Comment by AnonymerNiklasistanonym** [comment]
I noticed that too which was why I asked xD

I just added another note type to the program which is pretty much the same as the cloze note type but it has an additional field for the extra part.
This means that what is in the default note type the answer is now the extra field and both of them are only displayed after you press `Show answer`.

```sh
md2anki -v
# md2anki 3.0.18b
md2anki -anki-model md2anki_type_cloze_extra 04730_exam_blank.md -o-anki=test.apkg
```

It kinda adds a double `<hr>` with the test file but I feel like the default behavior should be adding one automatically
